# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirwayBill',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('batch', models.CharField(max_length=100, null=True, blank=True)),
                ('shippers_name_and_address', models.CharField(max_length=100, null=True, blank=True)),
                ('shippers_number', models.IntegerField(null=True, blank=True)),
                ('shippers_acct_no', models.CharField(max_length=100, null=True, blank=True)),
                ('consignees_name_and_address', models.CharField(max_length=100, null=True, blank=True)),
                ('consignees_number', models.IntegerField(null=True, blank=True)),
                ('consignees_acct_no', models.CharField(max_length=100, null=True, blank=True)),
                ('carrier_agent_name_and_city', models.CharField(max_length=100, null=True, blank=True)),
                ('carrier_agent_iata_code', models.CharField(max_length=100, null=True, blank=True)),
                ('agent_acct_no', models.IntegerField(null=True, blank=True)),
                ('airport_of_departure', models.CharField(max_length=100, null=True, blank=True)),
                ('origin_routing_code', models.CharField(max_length=100, null=True, blank=True)),
                ('origin_airline_carrier', models.CharField(max_length=100, null=True, blank=True)),
                ('destination_and_departure_routing_code1', models.CharField(max_length=100, null=True, blank=True)),
                ('second_airline_carrier', models.CharField(max_length=100, null=True, blank=True)),
                ('state_of_destination', models.CharField(max_length=100, null=True, blank=True)),
                ('third_airline_carrier', models.CharField(max_length=100, null=True, blank=True)),
                ('airport_of_destination', models.CharField(max_length=100, null=True, blank=True)),
                ('requested_flight_and_date1', models.CharField(max_length=100, null=True, blank=True)),
                ('requested_flight_and_date2', models.CharField(max_length=100, null=True, blank=True)),
                ('handling_info', models.CharField(max_length=100, null=True, blank=True)),
                ('issued_airline_carrier_and_address', models.CharField(max_length=100, null=True, blank=True)),
                ('accounting_info', models.CharField(max_length=100, null=True, blank=True)),
                ('ref_number', models.CharField(max_length=100, null=True, blank=True)),
                ('currency_code', models.CharField(max_length=100, null=True, blank=True)),
                ('value_for_carriage', models.CharField(max_length=100, null=True, blank=True)),
                ('value_for_custom', models.CharField(max_length=100, null=True, blank=True)),
                ('amount_of_insurance', models.IntegerField(null=True, blank=True)),
                ('number_of_pieces_to_ship', models.IntegerField(null=True, blank=True)),
                ('gross_weight', models.IntegerField(null=True, blank=True)),
                ('chargeable_rate', models.DecimalField(null=True, max_digits=20, decimal_places=2, blank=True)),
                ('note_on_the_package', models.CharField(max_length=200, null=True, blank=True)),
                ('nature_and_quantity_of_goods', models.CharField(max_length=200, null=True, blank=True)),
                ('regulation_of_goods', models.CharField(max_length=100, null=True, blank=True)),
                ('tracking_number_prefix', models.IntegerField(null=True, blank=True)),
                ('airline_tracking_number', models.IntegerField(null=True, blank=True)),
                ('other_charges_due_carrier', models.DecimalField(null=True, max_digits=20, decimal_places=2, blank=True)),
                ('total_prepaid', models.DecimalField(null=True, max_digits=20, decimal_places=2, blank=True)),
                ('place_of_execution', models.CharField(max_length=100, null=True, blank=True)),
                ('shippers_name', models.CharField(max_length=100, null=True, blank=True)),
                ('carrier_name', models.CharField(max_length=100, null=True, blank=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('shipping_method', models.CharField(default=b'Air Cargo', max_length=50)),
                ('carrier', models.CharField(max_length=50, null=True, blank=True)),
                ('awb_doc', models.FileField(null=True, upload_to=b'awb_doc', blank=True)),
                ('bol_doc', models.FileField(null=True, upload_to=b'bol_doc', blank=True)),
                ('batch_number', models.CharField(max_length=24, null=True, blank=True)),
                ('port_of_exit', models.CharField(max_length=50, null=True, blank=True)),
                ('port_of_arrival', models.CharField(max_length=50, null=True, blank=True)),
                ('booking_ref', models.CharField(max_length=50, null=True, blank=True)),
                ('departure_date', models.CharField(max_length=50, null=True, blank=True)),
                ('arrival_date', models.CharField(max_length=50, null=True, blank=True)),
                ('notes1', models.TextField(null=True, blank=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default=b'new', max_length=25)),
                ('batch_type', models.CharField(max_length=150, null=True, blank=True)),
                ('freight_type', models.CharField(max_length=50, null=True, blank=True)),
                ('awb', models.CharField(max_length=50, null=True, blank=True)),
                ('bol', models.CharField(max_length=50, null=True, blank=True)),
                ('total_pellets', models.CharField(max_length=50, null=True, blank=True)),
                ('shipping_cost_D', models.FloatField(default=0, max_length=50)),
                ('shipping_cost_N', models.FloatField(default=0, max_length=50)),
                ('clearing_cost', models.FloatField(default=0, max_length=50)),
                ('clearing_cost_N', models.FloatField(default=0, max_length=50)),
                ('harzmat_status', models.CharField(max_length=50, null=True, blank=True)),
                ('notes2', models.TextField(null=True, blank=True)),
                ('last_update', models.CharField(max_length=50, null=True)),
                ('expires_on', models.DateTimeField(null=True)),
                ('eta', models.IntegerField(null=True)),
                ('total_weight_P', models.FloatField(default=0.0, max_length=10)),
                ('total_weight_P_K', models.FloatField(default=0.0, max_length=10)),
                ('pkg_count', models.IntegerField(default=0)),
                ('total_value', models.FloatField(default=0.0, max_length=10)),
                ('total_value_bool', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('rank', models.CharField(max_length=30, null=True, blank=True)),
                ('subscriber', models.ForeignKey(blank=True, to='service_provider.Subscriber', null=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='BatchEditHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('batch_status', models.CharField(max_length=50, null=True, blank=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('eta', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(to='sokohaliAdmin.Batch')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'Batch Status History',
            },
        ),
        migrations.CreateModel(
            name='BatchPromo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('shipment_type', models.CharField(max_length=75)),
                ('available_space', models.CharField(max_length=125)),
                ('estimated_departure_time', models.DateTimeField()),
                ('current_rate', models.FloatField(default=0.0)),
                ('origin', models.CharField(max_length=125)),
                ('destination', models.CharField(max_length=125)),
                ('weight_range_at_rate', models.CharField(max_length=125)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CostCalcSettings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dim_weight_factor', models.FloatField(default=164, max_length=10)),
                ('lb_kg_factor', models.FloatField(default=0.45359, max_length=10)),
                ('kg_lb_factor', models.FloatField(default=2.20462, max_length=10)),
                ('dollar_exchange_rate', models.FloatField(default=239.0, max_length=10)),
                ('pound_naira_rate', models.FloatField(default=300.0, max_length=10)),
                ('vat_rate', models.FloatField(default=5, max_length=10)),
                ('vat_rate_1', models.FloatField(default=20, max_length=10)),
                ('insurance_rate', models.FloatField(default=6, max_length=10)),
                ('consolidation_fee', models.FloatField(default=15.0, max_length=10)),
                ('sc1_percentage', models.FloatField(default=10.0, max_length=10)),
                ('sc_dollar_rate_1', models.FloatField(default=5.0, max_length=10)),
                ('sc_dollar_rate_2', models.FloatField(default=1.0, max_length=10)),
                ('sc_dollar_rate_3', models.FloatField(default=0.75, max_length=10)),
                ('unit_strip_package_fee', models.FloatField(default=1.0, max_length=10)),
                ('order_TPC_1', models.FloatField(default=250.0, max_length=10)),
                ('order_TPC_2', models.FloatField(default=500.0, max_length=10)),
                ('order_TPC_3', models.FloatField(default=1000.0, max_length=10)),
                ('order_TPC_4', models.FloatField(default=5000.0, max_length=10)),
                ('service_charge_min_fee', models.FloatField(default=12.0, max_length=10)),
                ('handling_charge_fee', models.FloatField(default=5.0, max_length=10)),
                ('service_charge_rate_1', models.FloatField(default=7.0, max_length=10)),
                ('service_charge_rate_2', models.FloatField(default=6.5, max_length=10)),
                ('service_charge_rate_3', models.FloatField(default=6.0, max_length=10)),
                ('service_charge_rate_4', models.FloatField(default=5.5, max_length=10)),
                ('service_charge_rate_5', models.FloatField(default=5.0, max_length=10)),
                ('strip_package_fee_min', models.FloatField(default=5.0, max_length=10)),
                ('expressAir_min_fee', models.FloatField(default=50.0, max_length=10)),
                ('pickup_in_lag_rate', models.FloatField(default=0.0, max_length=10)),
                ('pickup_out_lag_rate', models.FloatField(default=1.0, max_length=10)),
                ('deliv_in_lag_rate', models.FloatField(default=1.5, max_length=10)),
                ('deliv_out_lag_rate', models.FloatField(default=2.5, max_length=10)),
                ('pickup_in_lag_min_fee', models.FloatField(default=0.0, max_length=10)),
                ('pickup_out_lag_min_fee', models.FloatField(default=8.0, max_length=10)),
                ('deliv_in_lag_min_fee', models.FloatField(default=5.0, max_length=10)),
                ('deliv_out_lag_min_fee', models.FloatField(default=20.0, max_length=10)),
                ('is_promo_on', models.BooleanField(default=False)),
                ('export_insurance_rate', models.FloatField(default=2, max_length=10)),
                ('export_consolidation_rate', models.FloatField(default=5, max_length=10)),
                ('export_min_shipping_charge', models.FloatField(default=6, max_length=5)),
                ('flat_cost_air_freight', models.FloatField(default=3.6, max_length=10)),
                ('demurrage_rate', models.FloatField(default=0.1, max_length=10)),
                ('demurrage_grace_period', models.IntegerField(default=7)),
                ('min_shipping_bal', models.FloatField(default=20, max_length=10)),
                ('vip_min_shipping_bal', models.FloatField(default=200, max_length=10)),
                ('kwd_val_percentage', models.FloatField(default=20, max_length=5)),
                ('customs_clearing_fee', models.FloatField(default=1040, max_length=10)),
                ('shipping_weight_threshold', models.FloatField(default=10, max_length=5)),
                ('cost_markup', models.FloatField(default=30.0, max_length=10)),
                ('currency', models.CharField(max_length=20, choices=[(b'naira', b'=N='), (b'pounds', b'\xc2\xa3'), (b'dollars', b'$')])),
                ('country', models.CharField(max_length=20, choices=[(b'Afghanistan', b'Afghanistan'), (b'Albania', b'Albania'), (b'Algeria', b'Algeria'), (b'Andorra', b'Andorra'), (b'Angola', b'Angola'), (b'Antigua and Barbuda', b'Antigua and Barbuda'), (b'Argentina', b'Argentina'), (b'Armenia', b'Armenia'), (b'Australia', b'Australia'), (b'Austria', b'Austria'), (b'Azerbaijan', b'Azerbaijan'), (b'Bahamas', b'Bahamas'), (b'Bahrain', b'Bahrain'), (b'Bangladesh', b'Bangladesh'), (b'Barbados', b'Barbados'), (b'Belarus', b'Belarus'), (b'Belgium', b'Belgium'), (b'Belize', b'Belize'), (b'Benin', b'Benin'), (b'Bhutan', b'Bhutan'), (b'Bolivia', b'Bolivia'), (b'Bosnia and Herzegovina', b'Bosnia and Herzegovina'), (b'Botswana', b'Botswana'), (b'Brazil', b'Brazil'), (b'Brunei', b'Brunei'), (b'Bulgaria', b'Bulgaria'), (b'Burkina Faso', b'Burkina Faso'), (b'Burundi', b'Burundi'), (b'Cabo Verde', b'Cabo Verde'), (b'Cambodia', b'Cambodia'), (b'Cameroon', b'Cameroon'), (b'Canada', b'Canada'), (b'Central African Republic', b'Central African Republic'), (b'Chad', b'Chad'), (b'Chile', b'Chile'), (b'China', b'China'), (b'Colombia', b'Colombia'), (b'Comoros', b'Comoros'), (b'Democratic Republic of the Congo', b'Democratic Republic of the Congo'), (b'Republic of the Congo', b'Republic of the Congo'), (b'Costa Rica', b'Costa Rica'), (b'Croatia', b'Croatia'), (b'Cuba', b'Cuba'), (b'Cyprus', b'Cyprus'), (b'Czech Republic', b'Czech Republic'), (b'Denmark', b'Denmark'), (b'Djibouti', b'Djibouti'), (b'Dominica', b'Dominica'), (b'Dominican Republic', b'Dominican Republic'), (b'Ecuador', b'Ecuador'), (b'Egypt', b'Egypt'), (b'El Salvador', b'El Salvador'), (b'Equatorial Guinea', b'Equatorial Guinea'), (b'Eritrea', b'Eritrea'), (b'Estonia', b'Estonia'), (b'Ethiopia', b'Ethiopia'), (b'Fiji', b'Fiji'), (b'Finland', b'Finland'), (b'France', b'France'), (b'Gabon', b'Gabon'), (b'Gambia', b'Gambia'), (b'Georgia', b'Georgia'), (b'Germany', b'Germany'), (b'Ghana', b'Ghana'), (b'Greece', b'Greece'), (b'Grenada', b'Grenada'), (b'Guatemala', b'Guatemala'), (b'Guinea', b'Guinea'), (b'Guinea-Bissau', b'Guinea-Bissau'), (b'Guyana', b'Guyana'), (b'Haiti', b'Haiti'), (b'Honduras', b'Honduras'), (b'Hungary', b'Hungary'), (b'Iceland', b'Iceland'), (b'India', b'India'), (b'Indonesia', b'Indonesia'), (b'Iran', b'Iran'), (b'Iraq', b'Iraq'), (b'Ireland', b'Ireland'), (b'Italy', b'Italy'), (b'Ivory Coast', b'Ivory Coast'), (b'Jamaica', b'Jamaica'), (b'Japan', b'Japan'), (b'Jordan', b'Jordan'), (b'Kazakhstan', b'Kazakhstan'), (b'Kenya', b'Kenya'), (b'Kiribati', b'Kiribati'), (b'Kosovo', b'Kosovo'), (b'Kuwait', b'Kuwait'), (b'Kyrgyzstan', b'Kyrgyzstan'), (b'Laos', b'Laos'), (b'Latvia', b'Latvia'), (b'Lebanon', b'Lebanon'), (b'Lesotho', b'Lesotho'), (b'Liberia', b'Liberia'), (b'Libya', b'Libya'), (b'Liechtenstein', b'Liechtenstein'), (b'Lithuania', b'Lithuania'), (b'Luxembourg', b'Luxembourg'), (b'Macedonia', b'Macedonia'), (b'Madagascar', b'Madagascar'), (b'Malawi', b'Malawi'), (b'Malaysia', b'Malaysia'), (b'Maldives', b'Maldives'), (b'Mali', b'Mali'), (b'Malta', b'Malta'), (b'Marshall Islands', b'Marshall Islands'), (b'Mauritania', b'Mauritania'), (b'Mauritius', b'Mauritius'), (b'Mexico', b'Mexico'), (b'Micronesia', b'Micronesia'), (b'Moldova', b'Moldova'), (b'Monaco', b'Monaco'), (b'Mongolia', b'Mongolia'), (b'Montenegro', b'Montenegro'), (b'Morocco', b'Morocco'), (b'Mozambique', b'Mozambique'), (b'Myanmar', b'Myanmar'), (b'Namibia', b'Namibia'), (b'Nauru', b'Nauru'), (b'Nepal', b'Nepal'), (b'Netherlands', b'Netherlands'), (b'New Zealand', b'New Zealand'), (b'Nicaragua', b'Nicaragua'), (b'Niger', b'Niger'), (b'Nigeria', b'Nigeria'), (b'North Korea', b'North Korea'), (b'Norway', b'Norway'), (b'Oman', b'Oman'), (b'Pakistan', b'Pakistan'), (b'Palau', b'Palau'), (b'Palestine', b'Palestine'), (b'Panama', b'Panama'), (b'Papua New Guinea', b'Papua New Guinea'), (b'Paraguay', b'Paraguay'), (b'Peru', b'Peru'), (b'Poland', b'Poland'), (b'Portugal', b'Portugal'), (b'Qatar', b'Qatar'), (b'Romania', b'Romania'), (b'Russia', b'Russia'), (b'Rwanda', b'Rwanda'), (b'Saint Kitts and Nevis', b'Saint Kitts and Nevis'), (b'Saint Lucia', b'Saint Lucia'), (b'Saint Vincent and the Grenadines', b'Saint Vincent and the Grenadines'), (b'Samoa', b'Samoa'), (b'San Marino', b'San Marino'), (b'Sao Tome and Principe', b'Sao Tome and Principe'), (b'Saudi Arabia', b'Saudi Arabia'), (b'Senegal', b'Senegal'), (b'Serbia', b'Serbia'), (b'Seychelles', b'Seychelles'), (b'Sierra Leone', b'Sierra Leone'), (b'Singapore', b'Singapore'), (b'Slovakia', b'Slovakia'), (b'Slovenia', b'Slovenia'), (b'Solomon Islands', b'Solomon Islands'), (b'Somalia', b'Somalia'), (b'South Africa', b'South Africa'), (b'South Korea', b'South Korea'), (b'South Sudan', b'South Sudan'), (b'Spain', b'Spain'), (b'Sri Lanka', b'Sri Lanka'), (b'Sudan', b'Sudan'), (b'Suriname', b'Suriname'), (b'Swaziland', b'Swaziland'), (b'Sweden', b'Sweden'), (b'Switzerland', b'Switzerland'), (b'Taiwan', b'Taiwan'), (b'Tajikistan', b'Tajikistan'), (b'Tanzania', b'Tanzania'), (b'Thailand', b'Thailand'), (b'Timor-Leste', b'Timor-Leste'), (b'Togo', b'Togo'), (b'Tonga', b'Tonga'), (b'Trinidad and Tobago', b'Trinidad and Tobago'), (b'Tunisia', b'Tunisia'), (b'Turkey', b'Turkey'), (b'Turkmenistan', b'Turkmenistan'), (b'Tuvalu', b'Tuvalu'), (b'Uganda', b'Uganda'), (b'Ukraine', b'Ukraine'), (b'United Arab Emirates', b'United Arab Emirates'), (b'United Kingdom', b'United Kingdom'), (b'United States', b'United States'), (b'Uruguay', b'Uruguay'), (b'Uzbekistan', b'Uzbekistan'), (b'Vanuatu', b'Vanuatu'), (b'Vatican City', b'Vatican City'), (b'Venezuela', b'Venezuela'), (b'Vietnam', b'Vietnam'), (b'Yemen', b'Yemen'), (b'Zambia', b'Zambia'), (b'Zimbabwe', b'Zimbabwe')])),
                ('marketer', models.ForeignKey(blank=True, to='service_provider.MarketingMember', null=True)),
            ],
            options={
                'verbose_name_plural': 'Cost Calc Settings',
            },
        ),
        migrations.CreateModel(
            name='ExportObjCostCalcSettings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dim_weight_factor', models.FloatField(default=164, max_length=10)),
                ('lb_kg_factor', models.FloatField(default=0.45359, max_length=10)),
                ('kg_lb_factor', models.FloatField(default=2.20462, max_length=10)),
                ('dollar_exchange_rate', models.FloatField(default=239.0, max_length=10)),
                ('pound_naira_rate', models.FloatField(default=300.0, max_length=10)),
                ('vat_rate', models.FloatField(default=5, max_length=10)),
                ('vat_rate_1', models.FloatField(default=20, max_length=10)),
                ('insurance_rate', models.FloatField(default=6, max_length=10)),
                ('consolidation_fee', models.FloatField(default=15.0, max_length=10)),
                ('sc1_percentage', models.FloatField(default=10.0, max_length=10)),
                ('sc_dollar_rate_1', models.FloatField(default=5.0, max_length=10)),
                ('sc_dollar_rate_2', models.FloatField(default=1.0, max_length=10)),
                ('sc_dollar_rate_3', models.FloatField(default=0.75, max_length=10)),
                ('unit_strip_package_fee', models.FloatField(default=1.0, max_length=10)),
                ('order_TPC_1', models.FloatField(default=250.0, max_length=10)),
                ('order_TPC_2', models.FloatField(default=500.0, max_length=10)),
                ('order_TPC_3', models.FloatField(default=1000.0, max_length=10)),
                ('order_TPC_4', models.FloatField(default=5000.0, max_length=10)),
                ('service_charge_min_fee', models.FloatField(default=12.0, max_length=10)),
                ('handling_charge_fee', models.FloatField(default=5.0, max_length=10)),
                ('service_charge_rate_1', models.FloatField(default=7.0, max_length=10)),
                ('service_charge_rate_2', models.FloatField(default=6.5, max_length=10)),
                ('service_charge_rate_3', models.FloatField(default=6.0, max_length=10)),
                ('service_charge_rate_4', models.FloatField(default=5.5, max_length=10)),
                ('service_charge_rate_5', models.FloatField(default=5.0, max_length=10)),
                ('strip_package_fee_min', models.FloatField(default=5.0, max_length=10)),
                ('expressAir_min_fee', models.FloatField(default=50.0, max_length=10)),
                ('pickup_in_lag_rate', models.FloatField(default=0.0, max_length=10)),
                ('pickup_out_lag_rate', models.FloatField(default=1.0, max_length=10)),
                ('deliv_in_lag_rate', models.FloatField(default=1.5, max_length=10)),
                ('deliv_out_lag_rate', models.FloatField(default=2.5, max_length=10)),
                ('pickup_in_lag_min_fee', models.FloatField(default=0.0, max_length=10)),
                ('pickup_out_lag_min_fee', models.FloatField(default=8.0, max_length=10)),
                ('deliv_in_lag_min_fee', models.FloatField(default=5.0, max_length=10)),
                ('deliv_out_lag_min_fee', models.FloatField(default=20.0, max_length=10)),
                ('is_promo_on', models.BooleanField(default=False)),
                ('export_insurance_rate', models.FloatField(default=2, max_length=10)),
                ('export_consolidation_rate', models.FloatField(default=5, max_length=10)),
                ('export_min_shipping_charge', models.FloatField(default=6, max_length=5)),
                ('flat_cost_air_freight', models.FloatField(default=3.6, max_length=10)),
                ('demurrage_rate', models.FloatField(default=0.1, max_length=10)),
                ('demurrage_grace_period', models.IntegerField(default=7)),
                ('min_shipping_bal', models.FloatField(default=20, max_length=10)),
                ('vip_min_shipping_bal', models.FloatField(default=200, max_length=10)),
                ('kwd_val_percentage', models.FloatField(default=20, max_length=5)),
                ('customs_clearing_fee', models.FloatField(default=1040, max_length=10)),
                ('shipping_weight_threshold', models.FloatField(default=10, max_length=5)),
                ('cost_markup', models.FloatField(default=30.0, max_length=10)),
                ('currency', models.CharField(max_length=20, choices=[(b'naira', b'=N='), (b'pounds', b'\xc2\xa3'), (b'dollars', b'$')])),
                ('country', models.CharField(max_length=20, choices=[(b'Afghanistan', b'Afghanistan'), (b'Albania', b'Albania'), (b'Algeria', b'Algeria'), (b'Andorra', b'Andorra'), (b'Angola', b'Angola'), (b'Antigua and Barbuda', b'Antigua and Barbuda'), (b'Argentina', b'Argentina'), (b'Armenia', b'Armenia'), (b'Australia', b'Australia'), (b'Austria', b'Austria'), (b'Azerbaijan', b'Azerbaijan'), (b'Bahamas', b'Bahamas'), (b'Bahrain', b'Bahrain'), (b'Bangladesh', b'Bangladesh'), (b'Barbados', b'Barbados'), (b'Belarus', b'Belarus'), (b'Belgium', b'Belgium'), (b'Belize', b'Belize'), (b'Benin', b'Benin'), (b'Bhutan', b'Bhutan'), (b'Bolivia', b'Bolivia'), (b'Bosnia and Herzegovina', b'Bosnia and Herzegovina'), (b'Botswana', b'Botswana'), (b'Brazil', b'Brazil'), (b'Brunei', b'Brunei'), (b'Bulgaria', b'Bulgaria'), (b'Burkina Faso', b'Burkina Faso'), (b'Burundi', b'Burundi'), (b'Cabo Verde', b'Cabo Verde'), (b'Cambodia', b'Cambodia'), (b'Cameroon', b'Cameroon'), (b'Canada', b'Canada'), (b'Central African Republic', b'Central African Republic'), (b'Chad', b'Chad'), (b'Chile', b'Chile'), (b'China', b'China'), (b'Colombia', b'Colombia'), (b'Comoros', b'Comoros'), (b'Democratic Republic of the Congo', b'Democratic Republic of the Congo'), (b'Republic of the Congo', b'Republic of the Congo'), (b'Costa Rica', b'Costa Rica'), (b'Croatia', b'Croatia'), (b'Cuba', b'Cuba'), (b'Cyprus', b'Cyprus'), (b'Czech Republic', b'Czech Republic'), (b'Denmark', b'Denmark'), (b'Djibouti', b'Djibouti'), (b'Dominica', b'Dominica'), (b'Dominican Republic', b'Dominican Republic'), (b'Ecuador', b'Ecuador'), (b'Egypt', b'Egypt'), (b'El Salvador', b'El Salvador'), (b'Equatorial Guinea', b'Equatorial Guinea'), (b'Eritrea', b'Eritrea'), (b'Estonia', b'Estonia'), (b'Ethiopia', b'Ethiopia'), (b'Fiji', b'Fiji'), (b'Finland', b'Finland'), (b'France', b'France'), (b'Gabon', b'Gabon'), (b'Gambia', b'Gambia'), (b'Georgia', b'Georgia'), (b'Germany', b'Germany'), (b'Ghana', b'Ghana'), (b'Greece', b'Greece'), (b'Grenada', b'Grenada'), (b'Guatemala', b'Guatemala'), (b'Guinea', b'Guinea'), (b'Guinea-Bissau', b'Guinea-Bissau'), (b'Guyana', b'Guyana'), (b'Haiti', b'Haiti'), (b'Honduras', b'Honduras'), (b'Hungary', b'Hungary'), (b'Iceland', b'Iceland'), (b'India', b'India'), (b'Indonesia', b'Indonesia'), (b'Iran', b'Iran'), (b'Iraq', b'Iraq'), (b'Ireland', b'Ireland'), (b'Italy', b'Italy'), (b'Ivory Coast', b'Ivory Coast'), (b'Jamaica', b'Jamaica'), (b'Japan', b'Japan'), (b'Jordan', b'Jordan'), (b'Kazakhstan', b'Kazakhstan'), (b'Kenya', b'Kenya'), (b'Kiribati', b'Kiribati'), (b'Kosovo', b'Kosovo'), (b'Kuwait', b'Kuwait'), (b'Kyrgyzstan', b'Kyrgyzstan'), (b'Laos', b'Laos'), (b'Latvia', b'Latvia'), (b'Lebanon', b'Lebanon'), (b'Lesotho', b'Lesotho'), (b'Liberia', b'Liberia'), (b'Libya', b'Libya'), (b'Liechtenstein', b'Liechtenstein'), (b'Lithuania', b'Lithuania'), (b'Luxembourg', b'Luxembourg'), (b'Macedonia', b'Macedonia'), (b'Madagascar', b'Madagascar'), (b'Malawi', b'Malawi'), (b'Malaysia', b'Malaysia'), (b'Maldives', b'Maldives'), (b'Mali', b'Mali'), (b'Malta', b'Malta'), (b'Marshall Islands', b'Marshall Islands'), (b'Mauritania', b'Mauritania'), (b'Mauritius', b'Mauritius'), (b'Mexico', b'Mexico'), (b'Micronesia', b'Micronesia'), (b'Moldova', b'Moldova'), (b'Monaco', b'Monaco'), (b'Mongolia', b'Mongolia'), (b'Montenegro', b'Montenegro'), (b'Morocco', b'Morocco'), (b'Mozambique', b'Mozambique'), (b'Myanmar', b'Myanmar'), (b'Namibia', b'Namibia'), (b'Nauru', b'Nauru'), (b'Nepal', b'Nepal'), (b'Netherlands', b'Netherlands'), (b'New Zealand', b'New Zealand'), (b'Nicaragua', b'Nicaragua'), (b'Niger', b'Niger'), (b'Nigeria', b'Nigeria'), (b'North Korea', b'North Korea'), (b'Norway', b'Norway'), (b'Oman', b'Oman'), (b'Pakistan', b'Pakistan'), (b'Palau', b'Palau'), (b'Palestine', b'Palestine'), (b'Panama', b'Panama'), (b'Papua New Guinea', b'Papua New Guinea'), (b'Paraguay', b'Paraguay'), (b'Peru', b'Peru'), (b'Poland', b'Poland'), (b'Portugal', b'Portugal'), (b'Qatar', b'Qatar'), (b'Romania', b'Romania'), (b'Russia', b'Russia'), (b'Rwanda', b'Rwanda'), (b'Saint Kitts and Nevis', b'Saint Kitts and Nevis'), (b'Saint Lucia', b'Saint Lucia'), (b'Saint Vincent and the Grenadines', b'Saint Vincent and the Grenadines'), (b'Samoa', b'Samoa'), (b'San Marino', b'San Marino'), (b'Sao Tome and Principe', b'Sao Tome and Principe'), (b'Saudi Arabia', b'Saudi Arabia'), (b'Senegal', b'Senegal'), (b'Serbia', b'Serbia'), (b'Seychelles', b'Seychelles'), (b'Sierra Leone', b'Sierra Leone'), (b'Singapore', b'Singapore'), (b'Slovakia', b'Slovakia'), (b'Slovenia', b'Slovenia'), (b'Solomon Islands', b'Solomon Islands'), (b'Somalia', b'Somalia'), (b'South Africa', b'South Africa'), (b'South Korea', b'South Korea'), (b'South Sudan', b'South Sudan'), (b'Spain', b'Spain'), (b'Sri Lanka', b'Sri Lanka'), (b'Sudan', b'Sudan'), (b'Suriname', b'Suriname'), (b'Swaziland', b'Swaziland'), (b'Sweden', b'Sweden'), (b'Switzerland', b'Switzerland'), (b'Taiwan', b'Taiwan'), (b'Tajikistan', b'Tajikistan'), (b'Tanzania', b'Tanzania'), (b'Thailand', b'Thailand'), (b'Timor-Leste', b'Timor-Leste'), (b'Togo', b'Togo'), (b'Tonga', b'Tonga'), (b'Trinidad and Tobago', b'Trinidad and Tobago'), (b'Tunisia', b'Tunisia'), (b'Turkey', b'Turkey'), (b'Turkmenistan', b'Turkmenistan'), (b'Tuvalu', b'Tuvalu'), (b'Uganda', b'Uganda'), (b'Ukraine', b'Ukraine'), (b'United Arab Emirates', b'United Arab Emirates'), (b'United Kingdom', b'United Kingdom'), (b'United States', b'United States'), (b'Uruguay', b'Uruguay'), (b'Uzbekistan', b'Uzbekistan'), (b'Vanuatu', b'Vanuatu'), (b'Vatican City', b'Vatican City'), (b'Venezuela', b'Venezuela'), (b'Vietnam', b'Vietnam'), (b'Yemen', b'Yemen'), (b'Zambia', b'Zambia'), (b'Zimbabwe', b'Zimbabwe')])),
            ],
            options={
                'verbose_name_plural': 'Export Cost Calc Records',
            },
        ),
        migrations.CreateModel(
            name='FedExLocation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('town_area', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('telephone', models.CharField(max_length=50, null=True, blank=True)),
                ('country', models.CharField(default=b'Nigeria', max_length=15, choices=[(b'', b'Select country'), (b'Nigeria', b'Nigeria')])),
                ('state', models.CharField(max_length=50, choices=[(b'', b'Select state'), (b'Abia', b'Abia'), (b'Abuja', b'Abuja'), (b'Adamawa', b'Adamawa'), (b'Akwa Ibom', b'Akwa Ibom'), (b'Anambra', b'Anambra'), (b'Bauchi', b'Bauchi'), (b'Bayelsa', b'Bayelsa'), (b'Benue', b'Benue'), (b'Borno', b'Borno'), (b'Cross River', b'Cross River'), (b'Delta', b'Delta'), (b'Ebonyi', b'Ebonyi'), (b'Edo', b'Edo'), (b'Ekiti', b'Ekiti'), (b'Enugu', b'Enugu'), (b'Gombe', b'Gombe'), (b'Imo', b'Imo'), (b'Jigawa', b'Jigawa'), (b'Kaduna', b'Kaduna'), (b'Kano', b'Kano'), (b'Katsina', b'Katsina'), (b'Kebbi', b'Kebbi'), (b'Kogi', b'Kogi'), (b'Kwara', b'Kwara'), (b'Lagos', b'Lagos'), (b'Nasarawa', b'Nasarawa'), (b'Niger', b'Niger'), (b'Ogun', b'Ogun'), (b'Ondo', b'Ondo'), (b'Osun', b'Osun'), (b'Oyo', b'Oyo'), (b'Plateau', b'Plateau'), (b'Rivers', b'Rivers'), (b'Sokoto', b'Sokoto'), (b'Taraba', b'Taraba'), (b'Yobe', b'Yobe'), (b'Zamfara', b'Zamfara')])),
                ('zone', models.CharField(default=b'', max_length=20, choices=[(b'LagosIntra-City', b'LagosIntra-City'), (b'West', b'West'), (b'East', b'East'), (b'North', b'North'), (b'FarEast', b'FarEast'), (b'FarNorth', b'FarNorth')])),
            ],
            options={
                'ordering': ['state'],
                'verbose_name_plural': 'FedEx Locations',
            },
        ),
        migrations.CreateModel(
            name='HomePageBkgdCity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('city', models.CharField(max_length=20)),
                ('bkgd_image', models.ImageField(upload_to=b'HomePageBkgdCity')),
            ],
            options={
                'verbose_name_plural': 'Home Page Background City',
            },
        ),
        migrations.CreateModel(
            name='NewFedExLocalFreightSettings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('within_500g_3kg_in_lag_rate', models.FloatField(default=600, max_length=5)),
                ('extra_kg_in_lag_rate', models.FloatField(default=150, max_length=5)),
                ('within_500g_3kg_out_lag_rate', models.FloatField(default=2000, max_length=5)),
                ('extra_kg_out_lag_rate', models.FloatField(default=250, max_length=5)),
                ('shippyme_markup', models.FloatField(default=30.0, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'New FedEx Local Freight Cost Settings',
            },
        ),
        migrations.CreateModel(
            name='NotifyUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('suite_no', models.CharField(max_length=150, null=True, blank=True)),
                ('name', models.CharField(max_length=150, null=True, blank=True)),
                ('address', models.CharField(max_length=250, null=True, blank=True)),
                ('last_four_digits', models.CharField(max_length=50, null=True, blank=True)),
                ('image_field', models.ImageField(null=True, upload_to=b'notifyUser-photo-id/%Y/%m/%d', blank=True)),
                ('item_description', models.CharField(max_length=350, null=True, blank=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=50, null=True, blank=True)),
                ('weight', models.DecimalField(null=True, max_digits=6, decimal_places=2, blank=True)),
                ('status', models.CharField(default=b'Received', max_length=50)),
                ('user', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingCountry',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('country', models.CharField(max_length=30)),
                ('currency_symbol', models.CharField(max_length=1)),
                ('currency_rep', models.CharField(max_length=20)),
                ('address', models.CharField(default=b'', max_length=300)),
                ('delivery_address', models.CharField(default=b'', max_length=300)),
                ('status', models.CharField(max_length=20, choices=[(b'', b'Select status'), (b'active', b'Active'), (b'inactive', b'Inactive')])),
                ('logo', models.ImageField(null=True, upload_to=b'OperatingCountry')),
                ('full_country_name', models.CharField(default=b'', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Operating Countries',
            },
        ),
        migrations.CreateModel(
            name='PreDefinedBoxes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('box_name', models.CharField(max_length=50)),
                ('box_length', models.DecimalField(max_digits=5, decimal_places=1)),
                ('box_width', models.DecimalField(max_digits=5, decimal_places=1)),
                ('box_height', models.DecimalField(max_digits=5, decimal_places=1)),
                ('box_weight', models.DecimalField(max_digits=5, decimal_places=1)),
                ('description', models.CharField(default=b'item', max_length=50)),
                ('quantity', models.CharField(default=b'1', max_length=5)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['box_name'],
                'verbose_name_plural': 'Pre-Defined Boxes',
            },
        ),
        migrations.CreateModel(
            name='ShippingKeyword',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('category', models.CharField(max_length=50)),
                ('keywords', models.TextField()),
                ('shipping_box', models.ForeignKey(to='sokohaliAdmin.PreDefinedBoxes')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('keywords', models.TextField(blank=True)),
                ('weight', models.DecimalField(max_digits=7, decimal_places=2)),
                ('Category', models.ForeignKey(related_name='categories', to='sokohaliAdmin.ShippingKeyword', null=True)),
            ],
            options={
                'verbose_name_plural': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Trucking',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('job_number', models.CharField(max_length=50, null=True, blank=True)),
                ('cargo_decsription', models.TextField(null=True, blank=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=50, null=True, blank=True)),
                ('done_by', models.CharField(max_length=50, null=True, blank=True)),
                ('actual_cargo_weight', models.DecimalField(default=1.0, max_digits=10, decimal_places=2)),
                ('total_cargo_weight', models.DecimalField(default=1.0, max_digits=10, decimal_places=2)),
                ('bol_number', models.CharField(max_length=50, null=True, blank=True)),
                ('origin', models.CharField(max_length=50, null=True, blank=True)),
                ('destination', models.CharField(max_length=50, null=True, blank=True)),
                ('pick_up_time', models.CharField(max_length=50, null=True, blank=True)),
                ('drop_off_time', models.CharField(max_length=50, null=True, blank=True)),
                ('time_to_pick_up', models.CharField(max_length=50, null=True, blank=True)),
                ('time_to_drop_off', models.CharField(max_length=50, null=True, blank=True)),
                ('status', models.CharField(default=b'New', max_length=20, null=True, blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('bol_image', models.ImageField(null=True, upload_to=b'BillofLaden', blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='batch_airwaybill',
            field=models.ForeignKey(blank=True, to='sokohaliAdmin.Batch', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set([('name',)]),
        ),
    ]
