# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
        ('sokohaliAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierLabel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tracking_id', models.CharField(max_length=50)),
                ('label', models.FileField(upload_to=b'shipping_labels/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Courier Package Label',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=10, choices=[(b'', b'Choose Title'), (b'Mr.', b'Mr.'), (b'Mrs.', b'Mrs.'), (b'Ms.', b'Ms.')])),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address_line1', models.CharField(max_length=300, null=True)),
                ('address_line2', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'Delivery Addresses',
            },
        ),
        migrations.CreateModel(
            name='DockReceipt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tracking_number', models.CharField(max_length=100, null=True, blank=True)),
                ('exporter_name_and_address', models.CharField(max_length=100, null=True, blank=True)),
                ('zip_code', models.CharField(max_length=100, null=True, blank=True)),
                ('consigned_to', models.CharField(max_length=100, null=True, blank=True)),
                ('notify_party_name_and_address', models.CharField(max_length=100, null=True, blank=True)),
                ('document_number', models.CharField(max_length=100, null=True, blank=True)),
                ('bl_or_awb_number', models.CharField(max_length=100, null=True, blank=True)),
                ('export_references', models.CharField(max_length=100, null=True, blank=True)),
                ('forwarding_agent_fmc_no', models.CharField(max_length=100, null=True, blank=True)),
                ('state_and_country_of_origin_or_ftz_number', models.CharField(max_length=100, null=True, blank=True)),
                ('domestic_routing', models.CharField(max_length=100, null=True, blank=True)),
                ('loading_pier', models.CharField(max_length=100, null=True, blank=True)),
                ('type_of_move', models.CharField(max_length=100, null=True, blank=True)),
                ('containerized', models.BooleanField(default=False)),
                ('precarriage_by', models.CharField(max_length=100, null=True, blank=True)),
                ('place_of_receipt_by_precarrier', models.CharField(max_length=100, null=True, blank=True)),
                ('exporting_carrier', models.CharField(max_length=100, null=True, blank=True)),
                ('port_of_loading', models.CharField(max_length=100, null=True, blank=True)),
                ('foreign_port_of_unloading', models.CharField(max_length=100, null=True, blank=True)),
                ('place_of_delivery_by_oncarrier', models.CharField(max_length=100, null=True, blank=True)),
                ('mks_nos', models.CharField(max_length=100, null=True, blank=True)),
                ('no_of_pkgs', models.IntegerField(null=True, blank=True)),
                ('description_of_package_and_goods', models.CharField(max_length=100, null=True, blank=True)),
                ('gross_weight', models.IntegerField(null=True, blank=True)),
                ('measurement', models.CharField(max_length=100, null=True, blank=True)),
                ('lighter_truck', models.CharField(max_length=100, null=True, blank=True)),
                ('arrived_date', models.CharField(max_length=100, null=True, blank=True)),
                ('arrived_time', models.CharField(max_length=100, null=True, blank=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('batch', models.CharField(max_length=100, null=True, blank=True)),
                ('unloaded_date', models.CharField(max_length=100, null=True, blank=True)),
                ('unloaded_time', models.CharField(max_length=100, null=True, blank=True)),
                ('checked_by', models.CharField(max_length=100, null=True, blank=True)),
                ('placed_location', models.CharField(max_length=100, null=True, blank=True)),
                ('receiving_clerk_name', models.CharField(max_length=100, null=True, blank=True)),
                ('date_from_receiving_clerk', models.CharField(max_length=100, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticPackage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tracking_number', models.CharField(max_length=20, null=True, blank=True)),
                ('weight_kg', models.DecimalField(max_digits=15, decimal_places=1)),
                ('weight_lb', models.DecimalField(max_digits=15, decimal_places=1)),
                ('amount', models.FloatField(default=0)),
                ('balance_paid', models.FloatField(default=0)),
                ('description', models.CharField(max_length=200, null=True, blank=True)),
                ('status', models.CharField(default=b'New', max_length=25)),
                ('deleted', models.BooleanField(default=False)),
                ('ordered', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('dropoff_address', models.ForeignKey(related_name='dropoff_address', blank=True, to='shipping.DeliveryAddress', null=True)),
                ('dropoff_center', models.ForeignKey(related_name='dropoff_center', blank=True, to='service_provider.LocalDistributorLocation', null=True)),
                ('marketer', models.ForeignKey(to='service_provider.MarketingMember', null=True)),
                ('pickup_address', models.ForeignKey(related_name='pickup_address', blank=True, to='shipping.DeliveryAddress', null=True)),
                ('pickup_center', models.ForeignKey(related_name='pickup_center', blank=True, to='service_provider.LocalDistributorLocation', null=True)),
                ('shipper', models.ForeignKey(to='service_provider.LocalDistributionMember', null=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropOffPostOffice',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=10, choices=[(b'', b'Choose Title'), (b'Mr.', b'Mr.'), (b'Mrs.', b'Mrs.'), (b'Ms.', b'Ms.')])),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address_line1', models.CharField(max_length=300, null=True)),
                ('address_line2', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Drop at Post Office Addresses',
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=10, choices=[(b'', b'Choose Title'), (b'Mr.', b'Mr.'), (b'Mrs.', b'Mrs.'), (b'Ms.', b'Ms.')])),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address_line1', models.CharField(max_length=300, null=True)),
                ('address_line2', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Package pick up addresses',
            },
        ),
        migrations.CreateModel(
            name='ReturnAddress',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=10, choices=[(b'', b'Choose Title'), (b'Mr.', b'Mr.'), (b'Mrs.', b'Mrs.'), (b'Ms.', b'Ms.')])),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address_line1', models.CharField(max_length=300, null=True)),
                ('address_line2', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'Return Addresses',
            },
        ),
        migrations.CreateModel(
            name='ShippingItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('origin', models.CharField(max_length=100, null=True, blank=True)),
                ('destination', models.CharField(max_length=100, null=True, blank=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier_tracking_number', models.CharField(max_length=500, null=True, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('total_value', models.FloatField(default=b'0', max_length=10)),
                ('total_value_N', models.FloatField(default=b'0', max_length=10)),
                ('status', models.CharField(default=b'Not yet Received', max_length=50)),
                ('status_2', models.CharField(default=b'New', max_length=50)),
                ('ordered', models.BooleanField(default=False)),
                ('created_by_admin', models.BooleanField(default=False)),
                ('item_type', models.CharField(default=b'Regular', max_length=30)),
                ('country', models.CharField(max_length=10, null=True, blank=True)),
                ('cat_num', models.CharField(max_length=250, null=True, blank=True)),
                ('weight', models.CharField(max_length=250, null=True, blank=True)),
                ('link', models.CharField(max_length=500, null=True, blank=True)),
                ('tag', models.CharField(max_length=20, null=True, blank=True)),
                ('amount_paid', models.FloatField(default=b'0', max_length=10)),
                ('balance', models.FloatField(default=b'0', max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('marketer', models.ForeignKey(blank=True, to='service_provider.MarketingMember', null=True)),
                ('notify', models.OneToOneField(null=True, blank=True, to='sokohaliAdmin.NotifyUser')),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'Shipping Items',
            },
        ),
        migrations.CreateModel(
            name='ShippingPackage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('box_length', models.DecimalField(null=True, max_digits=15, decimal_places=1, blank=True)),
                ('box_width', models.DecimalField(null=True, max_digits=15, decimal_places=1, blank=True)),
                ('box_height', models.DecimalField(null=True, max_digits=15, decimal_places=1, blank=True)),
                ('box_weight', models.DecimalField(default=0, null=True, max_digits=15, decimal_places=1, blank=True)),
                ('box_weight_K', models.DecimalField(default=0, max_digits=15, decimal_places=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('box_weight_Actual', models.DecimalField(max_digits=15, decimal_places=1)),
                ('box_weight_Actual_K', models.DecimalField(max_digits=15, decimal_places=1)),
                ('box_weight_Dim', models.DecimalField(default=1.0, max_digits=15, decimal_places=1)),
                ('box_weight_Dim_K', models.DecimalField(default=1.0, max_digits=15, decimal_places=1)),
                ('box_quantity', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=0)),
                ('status', models.CharField(default=b'New', max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('pkg_id', models.CharField(max_length=20, null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=20, null=True)),
                ('barcode_src', models.CharField(max_length=80, null=True, blank=True)),
                ('barcode_id', models.CharField(max_length=80, null=True, blank=True)),
                ('ordered', models.BooleanField(default=False)),
                ('insure', models.BooleanField(default=False)),
                ('insurance_fee_D', models.FloatField(default=0)),
                ('insurance_fee_N', models.FloatField(default=0)),
                ('VAT_charge_D', models.FloatField(default=0)),
                ('VAT_charge_N', models.FloatField(default=0)),
                ('pick_up_charge_D', models.FloatField(default=0)),
                ('pick_up_charge_N', models.FloatField(default=0)),
                ('service_charge_D', models.FloatField(default=0)),
                ('service_charge_N', models.FloatField(default=0)),
                ('user_total_payable_D', models.FloatField(default=0)),
                ('user_total_payable_N', models.FloatField(default=0)),
                ('admin_total_payable_D', models.FloatField(default=0)),
                ('admin_total_payable_N', models.FloatField(default=0)),
                ('balance_D', models.FloatField(default=0)),
                ('balance_N', models.FloatField(default=0)),
                ('balance_paid_D', models.FloatField(default=0)),
                ('balance_paid_N', models.FloatField(default=0)),
                ('courier_cost_D', models.FloatField(default=0)),
                ('courier_cost_N', models.FloatField(default=0)),
                ('intl_freight_D', models.FloatField(default=0)),
                ('intl_freight_N', models.FloatField(default=0)),
                ('local_freight_D', models.FloatField(default=0)),
                ('local_freight_N', models.FloatField(default=0)),
                ('coverage_amount_D', models.FloatField(default=0)),
                ('coverage_amount_N', models.FloatField(default=0)),
                ('tracking_number', models.CharField(max_length=50, null=True)),
                ('delivery_speed', models.CharField(max_length=50)),
                ('prepared_for_shipping', models.BooleanField(default=False)),
                ('assigned_to_batch', models.BooleanField(default=False)),
                ('syncedStatus', models.BooleanField(default=False)),
                ('barcode_base64', models.TextField()),
                ('pkg_image', models.ImageField(null=True, upload_to=b'pkg_images/%Y/%m/%d', blank=True)),
                ('shipping_method', models.CharField(max_length=50, choices=[(b'AF - OP', b'Air Freight - Office Pickup'), (b'AF - HD', b'Air Freight - Home delivery'), (b'SF - OP', b'Sea Freight - Office Pickup'), (b'SF - HD', b'Sea Freight - Home delivery'), (b'EX - OP', b'Express Air - Office Pickup'), (b'EX - HD', b'Express Air - Home delivery')])),
                ('is_estimate', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=30, null=True, blank=True)),
                ('created_by_admin', models.BooleanField(default=False)),
                ('has_promo', models.BooleanField(default=False)),
                ('promo_rate_per_lb', models.FloatField(default=0.0)),
                ('additional_charges_D', models.FloatField(default=0.0)),
                ('additional_charges_N', models.FloatField(default=0.0)),
                ('discount_D', models.FloatField(default=0.0)),
                ('discount_N', models.FloatField(default=0.0)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('shipment_type', models.CharField(default=b'Regular', max_length=25, null=True, blank=True)),
                ('handling_option', models.CharField(max_length=75, null=True, blank=True)),
                ('default_origin_address', models.CharField(max_length=150, null=True, blank=True)),
                ('default_destination_address', models.CharField(max_length=150, null=True, blank=True)),
                ('total_package_value', models.FloatField(default=0, max_length=50)),
                ('delivery_method', models.CharField(default=b'Office pickup', max_length=75, choices=[(b'Office pickup', b'Office pickup'), (b'Home delivery', b'Home delivery')])),
                ('override_payment', models.BooleanField(default=False)),
                ('batch_assigned', models.ForeignKey(blank=True, to='sokohaliAdmin.Batch', null=True)),
                ('costcalc_instance', models.ForeignKey(to='sokohaliAdmin.ExportObjCostCalcSettings', null=True)),
                ('delivery_address', models.ForeignKey(related_name='delivery_address', blank=True, to='shipping.DeliveryAddress', null=True)),
                ('destination_address', models.ForeignKey(blank=True, to='shipping.DeliveryAddress', null=True)),
                ('destination_warehouse', models.ForeignKey(related_name='pkg_destination_warehouse', blank=True, to='service_provider.WarehouseMember', null=True)),
                ('drop_off_location', models.ForeignKey(related_name='drop_off_location', verbose_name=b'Local distributor drop_off_location', to='service_provider.LocalDistributorLocation', null=True)),
                ('dropoff_postoffice', models.ForeignKey(related_name='dropoff_postoffice', blank=True, to='shipping.DropOffPostOffice', null=True)),
                ('local_pickup_address', models.ForeignKey(related_name='local_pickup_address', verbose_name=b'Local distributor address', blank=True, to='service_provider.LocalDistributorLocation', null=True)),
                ('message_center', models.ForeignKey(blank=True, to='general.MessageCenter', null=True)),
                ('origin_warehouse', models.ForeignKey(related_name='pkg_origin_warehouse', blank=True, to='service_provider.WarehouseMember', null=True)),
                ('pickup_location', models.ForeignKey(related_name='pickup_location', blank=True, to='shipping.PickupLocation', null=True)),
                ('return_address', models.ForeignKey(related_name='return_address', blank=True, to='shipping.ReturnAddress', null=True)),
                ('shipping_chain', models.ForeignKey(blank=True, to='service_provider.ShippingChain', null=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingPackageInvoice',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.FileField(upload_to=b'shipping_package_invoices/%Y/%m/%d')),
                ('package', models.ForeignKey(to='shipping.ShippingPackage', null=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Package Invoice',
            },
        ),
        migrations.AddField(
            model_name='shippingitem',
            name='package',
            field=models.ForeignKey(to='shipping.ShippingPackage', null=True),
        ),
        migrations.AddField(
            model_name='shippingitem',
            name='shipping_chain',
            field=models.ForeignKey(blank=True, to='service_provider.ShippingChain', null=True),
        ),
        migrations.AddField(
            model_name='shippingitem',
            name='user',
            field=models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='dockreceipt',
            name='shipping_package',
            field=models.ForeignKey(blank=True, to='shipping.ShippingPackage', null=True),
        ),
        migrations.AddField(
            model_name='courierlabel',
            name='package',
            field=models.ForeignKey(blank=True, to='shipping.ShippingPackage', null=True),
        ),
    ]
